SELECT * FROM EMPLOYEE WHERE NAME LIKE 'P%'

SELECT COUNT(SALARY) AS SALARY_COUNT FROM EMPLOYEE_SALARY WHERE ISPERM ='Y' AND SALARY > 5000;

SELECT * FROM EMPLOYEE WHERE EMAIL LIKE '%@GMAIL.COM'

SELECT * FROM EMPLOYEE E WHERE E.DEPT IN ('104','102')

SELECT DEPT_NAME FROM EMP_DEPT WHERE DEPT_ID='102'

SELECT SUM(SALARY) FROM EMPLOYEE_SALARY WHERE ISPERM='Y'


SELECT ES.* from EMPLOYEE_SALARY
LEFT JOIN MANAGER_SALARY USING (EMPID)
WHERE MANAGER_SALARY.EMPID is NULL

select E.* from
( select *,ROWNUM() OVER (order by id) as RowNum from EMPLOYEE ) E
where E.ROWNUM % 2 =1;

select salary
from EMPLOYEE_SALARY ES
where N-1=(
select count(distinct(emp2.salary))
from EMPLOYEE_SALARY ES2
where es2.salary > es.salary         b
)